AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RawPy Lambda Layer

Resources:
  RawPy38Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/layers/rawpy
      RetentionPolicy: Delete
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: makefile

  RawPy39Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/layers/rawpy
      RetentionPolicy: Delete
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: makefile

  RawPy38LayerArnSsmParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /layers/${AWS::StackName}/RawPy38Arn
      Type: String
      Value: !Ref RawPy38Layer
      Description: ARN of rawpy Lambda layer for Python 3.8

  RawPy39LayerArnSsmParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /layers/${AWS::StackName}/RawPy39Arn
      Type: String
      Value: !Ref RawPy39Layer
      Description: ARN of rawpy Lambda layer for Python 3.9

Outputs:
  RawPy38LayerArnOutput:
    Description: ARN of rawpy Lambda layer for Python 3.8
    Value: !Ref RawPy38Layer
    Export:
      Name: !Sub "${AWS::StackName}-RawPy38LayerArnOutput"

  RawPy39LayerArnOutput:
    Description: ARN of rawpy Lambda layer for Python 3.9
    Value: !Ref RawPy39Layer
    Export:
      Name: !Sub "${AWS::StackName}-RawPy39LayerArnOutput"
