build-RawPy38Layer:
	yum install -y LibRaw.x86_64
	mkdir -p "$(ARTIFACTS_DIR)/python"
	pip3 install rawpy --target "$(ARTIFACTS_DIR)/python"

build-RawPy39Layer:
	yum install -y LibRaw.x86_64
	mkdir -p "$(ARTIFACTS_DIR)/python"
	pip3 install rawpy --target "$(ARTIFACTS_DIR)/python"